config/urls.py
from django.contrib import admin
from django.urls import path,include
from notes.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('notes/', include('notes.urls')),
    path('tasks/', include('tasks.urls')),
]

notes/urls.py
from django.urls import path
from . import views


app_name = 'notes'

urlpatterns = [
    path('list', views.note_list, name='list'),
    path('create/', views.note_form, name='create'),
    path('detail/<int:pk>/', views.note_detail, name='detail'),
    path('update/<int:pk>/', views.note_update, name='update'),
    path('delete/<int:pk>/', views.note_delete, name='delete'),
]

tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('list/', views.task_list, name='list'),
    path('create/', views.task_form, name='create'),
    path('detail/<int:pk>/', views.task_detail, name='detail'),
    path('update/<int:pk>/', views.task_update, name='update'),
    path('delete/<int:pk>/', views.task_delete, name='delete'),
]

notes/models.py
from django.db import models
from django.shortcuts import reverse


class Note(models.Model):
    note_title = models.CharField(max_length=100)
    content = models.TextField()

    def get_detail_url(self):
        return reverse('notes:detail', args=[self.pk])

    def get_update_url(self):
        return reverse('notes:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('notes:delete', args=[self.pk])

tasks/models.py
from django.db import models
from django.shortcuts import reverse


class Task(models.Model):
    tasks_title = models.CharField(max_length=100)
    due_date = models.DateTimeField()
    description = models.TextField()

    def get_detail_url(self):
        return reverse('tasks:detail', args=[self.pk])

    def get_update_url(self):
        return reverse('tasks:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('tasks:delete', args=[self.pk])

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Note


def home(request):
    return render(request, 'index.html')

def note_list(request):
    notes = Note.objects.all()
    ctx = {'notes': notes}
    return render(request, 'notes/note-list.html', ctx)

def note_form(request):
    if request.method == 'POST':
        note_title = request.POST.get('note_title')
        content = request.POST.get('content')
        if note_title and content:
            Note.objects.create(
                note_title=note_title,
                content=content,
            )
            return redirect('notes:list')
    return render(request, 'notes/note-form.html')

def note_detail(request, pk):
    note = get_object_or_404(Note, pk=pk)
    ctx = {'note': note}
    return render(request, 'notes/note-detail.html', ctx)

def note_update(request, pk):
    note = get_object_or_404(Note, pk=pk)
    if request.method == 'POST':
        note_title = request.POST.get('note_title')
        content = request.POST.get('content')
        if note_title and content:
            note.note_title=note_title
            note.content=content
            note.save()
            return redirect(note.get_detail_url())
    ctx = {'note': note}
    return render(request, 'notes/note-form.html', ctx)

def note_delete(request, pk):
    note = get_object_or_404(Note, pk=pk)
    note.delete()
    return redirect('notes:list')

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Task


def task_list(request):
    tasks = Task.objects.all()
    ctx = {'tasks': tasks}
    return render(request, 'tasks/task-list.html', ctx)

def task_form(request):
    if request.method == 'POST':
        tasks_title = request.POST.get('tasks_title')
        due_date = request.POST.get('due_date')
        description = request.POST.get('description')
        if tasks_title and due_date and description:
            Task.objects.create(
                tasks_title=tasks_title,
                due_date=due_date,
                description=description
            )
            return redirect('tasks:list')
    return render(request, 'tasks/task-form.html')

def task_detail(request, pk):
    task = get_object_or_404(Task, pk=pk)
    ctx = {'task': task}
    return render(request, 'tasks/task-detail.html', ctx)

def task_update(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        tasks_title = request.POST.get('tasks_title')
        due_date = request.POST.get('due_date')
        description = request.POST.get('description')
        if tasks_title and due_date and description:
            task.tasks_title=tasks_title
            task.due_date=due_date
            task.description=description
            task.save()
            return redirect(task.get_detail_url())
    ctx = {'task': task}
    return render(request, 'tasks/task-form.html', ctx)

def task_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.delete()
    return redirect('tasks:list')

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="home">
        <h1>Welcome to the Home Page</h1>
            <li><a href="{% url 'notes:list' %}">Go to Notes List</a></li>
            <li><a href="{% url 'tasks:list' %}">Go to Tasks List</a></li>

</body>
</html>

templates/notes/note-detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Note Detail</title>
    <link rel="stylesheet" href="{% static 'css/notes/note-detail.css' %}">
</head>
<body>
    <div class="detail-container">
        <h1>Note Detail</h1>
        <p><span>Note:</span> {{ note.note_title }}</p>
        <p><span>Content:</span> {{ note.content }}</p>

        <button class="update-btn"><a href="{{ note.get_update_url }}" class="update-btn">Update</a></button>
        <button class="delete-btn"><a href="{{ note.get_delete_url }}" class="delete-btn">Delete</a></button>
        <button class="back-btn"><a href="{% url 'notes:list' %}" class="back-btn">Back to List</a></button>
    </div>
</body>
</html>

templates/notes/note-form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if note %}Update Note{% else %}Create Note{% endif %}</title>
    <link rel="stylesheet" href="{% static 'css/notes/note-form.css' %}">
</head>
<body>
    <div class="form-container">
        <h1>{% if note %}Update Note{% else %}Create Note{% endif %}</h1>
        <form method="post" >
            {% csrf_token %}
            <label for="note_title">Note Title</label>
            <input type="text" id="note_title" name="note_title" placeholder="Enter title..." required value="{{ note.note_title }}">
            <br><br>
            <label for="content">Content</label>
            <textarea id="content" name="content" rows="5" placeholder="Enter content..." required>{{ note.content }}</textarea>

            {% if note %}
            <button type="submit" class="update-btn">Update Note</button>
            <button class="back-det1"><a href="{{ note.get_detail_url }}" class="back-det">Back to Detail</a></button>
            {% else %}
            <button type="submit" class="create-btn">Create Note</button>
            <button class="back-btn"><a href="{% url 'notes:list' %}" class="back-btn">Back to List</a></button>
            {% endif %}
        </form>
    </div>
</body>
</html>

templates/notes/note-list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Note List</title>
    <link rel="stylesheet" href="{% static 'css/notes/note-list.css' %}">
</head>
<body>
    <div class="note">
        <h1>Note List</h1>
        <a href="{% url 'notes:create' %}" class="create-note">Create Note</a>
        <ul class="note-list">
            {% for note in notes %}
            <li><a href="{{ note.get_detail_url }}">{{ note.note_title | upper }}</a></li>
            {% empty %}
            <li>Not Found</li>
            {% endfor %}
        </ul>

        <a href="{% url 'home' %}" class="back-home">Back to Home</a>
    </div>
</body>
</html>

templates/tasks/task-detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Detail</title>
    <link rel="stylesheet" href="{% static 'css/tasks/task-detail.css' %}">
</head>
<body>
    <div class="detail-container">
        <h1>Task Detail</h1>
        <p><span>Note:</span> {{ task.tasks_title }}</p>
        <p><span>Due Date:</span> {{ task.due_date | date:"Y~m~d" }}</p>
        <p><span>Description:</span> {{ task.description }}</p>

        <button class="update-btn"><a href="{{ task.get_update_url }}" class="update-btn">Update</a></button>
        <button class="delete-btn"><a href="{{ task.get_delete_url }}" class="delete-btn">Delete</a></button>
        <button class="back-btn"><a href="{% url 'tasks:list' %}" class="back-btn">Back to List</a></button>
    </div>
</body>
</html>

templates/tasks/task-form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if task %}Update Task{% else %}Create Task{% endif %}</title>
    <link rel="stylesheet" href="{% static 'css/tasks/task-form.css' %}">
</head>
<body>
    <div class="form-container">
        <h1>{% if task %}Update Task{% else %}Create Task{% endif %}</h1>
        <form method="post" >
            {% csrf_token %}
            <label for="tasks_title">Tasks Title</label>
            <input type="text" id="tasks_title" name="tasks_title" placeholder="Enter title..." required value="{{ task.tasks_title }}">
            <br><br>
            <label for="due_date">Due Date</label>
            <input type="date" id="due_date" name="due_date" placeholder="Y-m-d" required value="{{ task.due_date }}">
            <br><br>
            <label for="description">Content</label>
            <textarea id="description" name="description" rows="5" placeholder="Enter description..." required>{{ task.description }}</textarea>
            {% if note %}
            <button type="submit" class="update-btn">Update Task</button>
            <button class="back-det1"><a href="{{ task.get_detail_url }}" class="back-det">Back to Detail</a></button>
            {% else %}
            <button type="submit" class="create-btn">Create Task</button>
            <button class="back-btn"><a href="{% url 'tasks:list' %}" class="back-btn">Back to List</a></button>
            {% endif %}
        </form>
    </div>
</body>
</html>

templates/tasks/task-list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks List</title>
    <link rel="stylesheet" href="{% static 'css/tasks/task-list.css' %}">
</head>
<body>
    <div class="container">
        <h1>Tasks List</h1>
        <a href="{% url 'tasks:create' %}" class="create-task">Create Task</a>
        <ul class="task-list">
            {% for task in tasks %}
            <li><a href="{{ task.get_detail_url }}">{{ task.tasks_title }}</a></li>
            {% empty %}
            <li>Not Found</li>
            {% endfor %}
        </ul>

        <a href="{% url 'home' %}" class="back-home">Back to Home</a>
    </div>
</body>
</html>